### ISSUE TITLE
post.getTopic needs to return vote_choice

### ISSUE THREAD

**Issue by NathanYocum** [LectureGoggles/FlaskAPI#61]
Causing a small bug on the frontend right now

**Comment by zackjohnson8** [comment]
That bug is because we don't have an upvote system added to topics. Did you want to add the ability to upvote topics?

**Comment by NathanYocum** [comment]
No this is for when we filter the posts by topic

**Comment by zackjohnson8** [comment]
Got you the topic_id returning on that. Must of missed that with all the other bits returned.
